// This file has been autogenerated from parsing an Objective-C header file added in Xcode.using System;
using System;
using System.Collections.Generic;
using System.Linq;
#if __UNIFIED__
using Foundation;
using UIKit;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
#endif
using Xamarin.Themes;
using ThemeSample.Model;

namespace ThemeSample {
	public partial class DetailThemeiPadController : UIViewController {
		public DetailThemeiPadController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			if (PodradioTheme.IsIOS7)
			{
				this.EdgesForExtendedLayout = UIRectEdge.None;
			}

			var navImage = PodradioTheme.SharedTheme.NavigationBackgroundForSplitView ();
			NavigationController.NavigationBar.SetBackgroundImage (navImage, UIBarMetrics.Default);

			var toolbarImg = PodradioTheme.SharedTheme.ToolbarBackgroundForSplitView ();
			ToolbarBottom.SetBackgroundImage (toolbarImg, UIToolbarPosition.Bottom, UIBarMetrics.Default);
			GenreLabel.BackgroundColor = UIColor.Clear;
			PodradioTheme.Apply (View);

			GenreLabel.TextColor = ColorSwitcher.TintColor;
		}

		internal void LoadDataIntoView (Track track)
		{
			if (track == null)
				throw new ArgumentNullException ("track");

			this.Title = track.Name;
			ArtistLabel.Text = track.Artist;
			TrackLabel.Text = track.Name;
			GenreLabel.Text = track.Genre;

			AlbumImageView.Image = track.LargeImage;

			if (masterPopover != null)
				masterPopover.Dismiss (true);
		}

		UIPopoverController masterPopover;

		[Export ("splitViewController:willHideViewController:withBarButtonItem:forPopoverController:")]
		void WillHideViewController (UISplitViewController svc, UIViewController aViewController, UIBarButtonItem barButtonItem, UIPopoverController pc)
		{
			barButtonItem.Title = "Master";
			var bItems = NavigationItem.RightBarButtonItems;
			var items = bItems != null ? bItems.ToList () : new List<UIBarButtonItem> ();

			items.Insert (0, barButtonItem);
			NavigationItem.LeftBarButtonItems = items.ToArray ();

			masterPopover = pc;
		}

		[Export ("splitViewController:willShowViewController:invalidatingBarButtonItem:")]
		public void WillShowViewController (UISplitViewController svc, UIViewController aViewController, UIBarButtonItem button)
		{
			var tmp = NavigationItem.RightBarButtonItems;
			var items = tmp != null ? tmp.ToList () : new List<UIBarButtonItem> ();
			items.Remove (button);
			NavigationItem.LeftBarButtonItems = items.ToArray ();
			masterPopover = null;
		}

		[Obsolete ("Deprecated in iOS 6.0")]
		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();
			ReleaseDesignerOutlets ();
		}

		[Obsolete ("Deprecated in iOS6. Replace it with both GetSupportedInterfaceOrientations and PreferredInterfaceOrientationForPresentation")]
		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{
			return true;
		}
	}
}
