// This file has been autogenerated from parsing an Objective-C header file added in Xcode.using System;
using System;
using System.Collections.Generic;
#if __UNIFIED__
using Foundation;
using UIKit;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
#endif
using Xamarin.Themes;
using ThemeSample.Model;

namespace ThemeSample {
	public partial class MasterViewController : UIViewController {
		public MasterViewController (IntPtr handle) : base (handle)
		{
		}

		List<Track> tracks;
		UILabel title;

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			tracks = DataLoader.LoadSampleData ();

			if (PodradioTheme.IsIOS7)
			{
				this.EdgesForExtendedLayout = UIRectEdge.None;
			}

			var navImage = PodradioTheme.SharedTheme.NavigationBackgroundForSplitView (true);
			NavigationController.NavigationBar.SetBackgroundImage (navImage, UIBarMetrics.Default);

			var toolbarImg = PodradioTheme.SharedTheme.ToolbarBackgroundForSplitView (true);
			ToolbarBottom.SetBackgroundImage (toolbarImg, UIToolbarPosition.Bottom, UIBarMetrics.Default);

			TracksTableView.WeakDelegate = this;
			TracksTableView.WeakDataSource = this;

			PodradioTheme.Apply (View);


			title = new UILabel ();
			title.BackgroundColor = UIColor.Clear;
			title.Font = PodradioTheme.SharedTheme.MainFont;
			title.ShadowColor = UIColor.Black;
			title.TextAlignment = UITextAlignment.Center;
			title.TextColor = UIColor.White;

			NavigationItem.TitleView = title;
			title.Text = "Albums";
			title.SizeToFit ();

		}

		const string CellIdentifier = "MasterCell";

		[Export ("tableView:cellForRowAtIndexPath:")]
		UITableViewCell CellForRow (UITableView tableView, NSIndexPath indexPath)
		{
			var track = tracks [indexPath.Row];

			var cell = tableView.DequeueReusableCell (CellIdentifier) as MasterCell;

			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			cell.Init (track);

			return cell;
		}

		[Export ("tableView:heightForRowAtIndexPath:")]
		float HeightForRow (UITableView tableView, NSIndexPath indexPath)
		{
			return 84;
		}

		[Export ("tableView:numberOfRowsInSection:")]
		int NumberOfRows (UITableView tableView, int section)
		{
			return tracks.Count;
		}

		[Export ("tableView:didSelectRowAtIndexPath:")]
		void DidSelectRow (UITableView tableView, NSIndexPath indexPath)
		{
			var track = tracks [indexPath.Row];

			if (Detail != null) 
				Detail.LoadDataIntoView (track);
		}

		public DetailThemeiPadController Detail { get; set; }

		[Obsolete ("Deprecated in iOS 6.0")]
		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();
			ReleaseDesignerOutlets ();
		}

		[Obsolete ("Deprecated in iOS6. Replace it with both GetSupportedInterfaceOrientations and PreferredInterfaceOrientationForPresentation")]
		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{
			return true;
		}
	}
}
