// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using System.Drawing;
#if __UNIFIED__
using Foundation;
using UIKit;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
#endif
using Xamarin.Themes;
using ThemeSample.Model;

namespace ThemeSample {
	public partial class DetailThemeController : UIViewController {
		Track track;

		public DetailThemeController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			var edit = new UIBarButtonItem (UIBarButtonSystemItem.Add);
			NavigationItem.SetRightBarButtonItem (edit, false);



			scrollView.ContentSize = new SizeF (320, 550);
			PodradioTheme.Apply (scrollView as UIView);

			base.ViewDidLoad ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			this.Title = track.Name;

			artistLabel.Text = track.Artist;
			trackLabel.Text = track.Name;
			genreLabel.Text = track.Genre;
			albumImageView.Image = track.LargeImage;
		}

		internal void SetTrack (Track trackToDetail)
		{
			if (trackToDetail == null)
				throw new ArgumentNullException ("trackToDetail");
			track = trackToDetail;
		}

		[Obsolete ("Deprecated in iOS 6.0")]
		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();
			ReleaseDesignerOutlets ();
		}

		[Obsolete ("Deprecated in iOS6. Replace it with both GetSupportedInterfaceOrientations and PreferredInterfaceOrientationForPresentation")]
		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{
			return true;
		}
	}
}
