// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using System.Collections.Generic;
#if __UNIFIED__
using Foundation;
using UIKit;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
#endif
using Xamarin.Themes;
using ThemeSample.Model;

namespace ThemeSample {
	public partial class ThemeListController : UIViewController {
		List<Track> tracks;
		const string CellIdentifier = "ThemeListCell";

		public ThemeListController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.Title = "Artists";

			tracks = DataLoader.LoadSampleData ();
			tableListView.WeakDelegate = this;
			tableListView.WeakDataSource = this;

			tableListView.BackgroundColor = UIColor.Clear;
			tableListView.SeparatorStyle = UITableViewCellSeparatorStyle.None;

			var itemBtn = new UIBarButtonItem ("Item", UIBarButtonItemStyle.Plain, null);
			NavigationItem.SetRightBarButtonItem (itemBtn, false);

			PodradioTheme.Apply (View);
		}

		[Obsolete ("Deprecated in iOS 6.0")]
		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();
			ReleaseDesignerOutlets ();
		}

		[Obsolete ("Deprecated in iOS6. Replace it with both GetSupportedInterfaceOrientations and PreferredInterfaceOrientationForPresentation")]
		public override bool ShouldAutorotateToInterfaceOrientation (UIInterfaceOrientation toInterfaceOrientation)
		{
			return true;
		}

		[Export ("tableView:cellForRowAtIndexPath:")]
		UITableViewCell CellForRow (UITableView tableView, NSIndexPath indexPath)
		{
			var track = tracks [indexPath.Row];

			var cell = tableView.DequeueReusableCell (CellIdentifier) as ThemeListCell;
			
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			cell.Init (track);
			
			return cell;
		}

		[Export ("tableView:heightForRowAtIndexPath:")]
		float HeightForRow (UITableView tableView, NSIndexPath indexPath)
		{
			return 77;
		}

		[Export ("tableView:numberOfRowsInSection:")]
		int NumberOfRows (UITableView tableView, int section)
		{
			return tracks.Count;
		}

		[Export ("tableView:didSelectRowAtIndexPath:")]
		void DidSelectRow (UITableView tableView, NSIndexPath indexPath)
		{
			PerformSegue ("detail", this);
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);
			var detail = segue.DestinationViewController as DetailThemeController;

			var track = tracks [tableListView.IndexPathForSelectedRow.Row];

			if (detail != null) 
				detail.SetTrack (track);

		}
	}
}
