#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Pinterest.App.XamarinAndroid.Resource", IsApplication=true)]

namespace Pinterest.App.XamarinAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int button_text_plain = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int text_medium = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int ui_bg_light = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ui_bg_medium_gray = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int button_height = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int button_side_padding = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int global_padding = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int image_height = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int row_height = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int xamarin_x = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int desc_tv = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int gallery_bt = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int list = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int pin_bt = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int source_iv = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int uri_tv = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_demo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_demo_from_gallery = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_demo_listview = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_demo_simple = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int listview_item = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int gallery_name = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int image_uri = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int listview_name = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int menu_settings = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int pin_desc_gallery = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int pin_desc_hint = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int pin_desc_kitten = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int pin_gallery = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int pin_image = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int simple_name = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int button_plain = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
